#
#  Podfile
#  Dock
#
#  Created by Pierluigi Galdi on 14/05/2020.
#  Copyright © 2020 Pierluigi Galdi. All rights reserved.
# 

platform :osx, '10.15'

target 'Dock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dock
  pod 'PockKit', '0.3.0'
  pod 'TinyConstraints'

end

post_install do |_installer|
  system('ruby', File.expand_path('../../scripts/patch-pockkit-resource-usage.rb', __dir__), __dir__)
end
